// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package urls_checker

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5e01bfc2DecodeUrlsCheckerInternalAppUrlsChecker(in *jlexer.Lexer, out *UrlResponseBody) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "location":
			out.Location = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5e01bfc2EncodeUrlsCheckerInternalAppUrlsChecker(out *jwriter.Writer, in UrlResponseBody) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"location\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Location))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UrlResponseBody) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5e01bfc2EncodeUrlsCheckerInternalAppUrlsChecker(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UrlResponseBody) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5e01bfc2EncodeUrlsCheckerInternalAppUrlsChecker(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UrlResponseBody) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5e01bfc2DecodeUrlsCheckerInternalAppUrlsChecker(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UrlResponseBody) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5e01bfc2DecodeUrlsCheckerInternalAppUrlsChecker(l, v)
}
func easyjson5e01bfc2DecodeUrlsCheckerInternalAppUrlsChecker1(in *jlexer.Lexer, out *UrlRequestBody) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "domain":
			out.Domain = string(in.String())
		case "path":
			out.Path = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5e01bfc2EncodeUrlsCheckerInternalAppUrlsChecker1(out *jwriter.Writer, in UrlRequestBody) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"domain\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"path\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Path))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UrlRequestBody) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5e01bfc2EncodeUrlsCheckerInternalAppUrlsChecker1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UrlRequestBody) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5e01bfc2EncodeUrlsCheckerInternalAppUrlsChecker1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UrlRequestBody) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5e01bfc2DecodeUrlsCheckerInternalAppUrlsChecker1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UrlRequestBody) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5e01bfc2DecodeUrlsCheckerInternalAppUrlsChecker1(l, v)
}
